In [122]:
from pathlib import Path
import pandas as pd
import numpy as np

In [128]:
data_dir = Path('../data/original')
benchmark_a = data_dir / 'submission_6750a.csv'
benchmark_b = data_dir / 'submission_6750b.csv'
benchmark_c = data_dir / 'submission_6752.csv'
benchmark_d = data_dir / 'submission_6753.csv'
benchmark_e = data_dir / 'submission_6756.csv'
benchmark_f = data_dir / 'submission_6757.csv'
candidate = data_dir / 'submission.csv'

In [129]:
dfa = pd.read_csv(benchmark_a).set_index('Image_Label')
dfb = pd.read_csv(benchmark_b).set_index('Image_Label')
dfc = pd.read_csv(benchmark_c).set_index('Image_Label')
dfd = pd.read_csv(benchmark_d).set_index('Image_Label')
dfe = pd.read_csv(benchmark_e).set_index('Image_Label')
dff = pd.read_csv(benchmark_f).set_index('Image_Label')
dfz = pd.read_csv(candidate).set_index('Image_Label')

In [130]:
dfx = pd.concat([dfa, dfb, dfc, dfd, dfe, dff], axis=1)
common = dfx.isnull().apply(lambda row: not row.any(), axis=1)
print(common.sum())

5578


In [131]:
benchmarks = [dfa, dfb, dfc, dfd, dfe, dff]
for df in benchmarks:
    df['positive'] = pd.notna(df)

In [132]:
for df in benchmarks:
    diff = (common * -1) + df['positive']
    print(f'Removed: {(diff == -1).sum()}')
    print(f'Added: {(diff == 1).sum()}')

Removed: 0
Added: 338
Removed: 0
Added: 116
Removed: 0
Added: 202
Removed: 0
Added: 266
Removed: 0
Added: 221
Removed: 0
Added: 187


In [124]:
dfz['positive'] = pd.notna(dfz)
diff = (common * -1) + dfz['positive']
print(f'Removed: {(diff == -1).sum()}')
print(f'Added: {(diff == 1).sum()}')
for idx, value in (diff == -1).iteritems():
    if value:
        print(idx)

Removed: 0
Added: 159


In [133]:
dfz['positive'] = pd.notna(dfz)
diff = (dff['positive'] * -1) + dfz['positive']
print(f'Removed: {(diff == -1).sum()}')
print(f'Added: {(diff == 1).sum()}')

Removed: 152
Added: 240


In [113]:
count_a = np.array([1246, 1365, 1226, 2079])
count_b = np.array([1189, 1316, 1190, 1999])
count_c = np.array([1206, 1359, 1185, 2030])
count_d = np.array([1236, 1367, 1212, 2029])
count_e = np.array([1210, 1358, 1203, 2028])
avg = np.stack([count_a, count_b, count_c, count_d, count_e], axis=0).mean(axis=0)
avg

array([1217.4, 1353. , 1203.2, 2033. ])

In [6]:
xor = np.logical_xor(dfb['null'].values, dfc['null'].values)
xor.sum()

307

In [14]:
N_TEST = 3698
TRAIN_DIST = np.array([
    0.5014424810674359,
    0.4264334655607645,
    0.5299314821492968,
    0.6763433104940497
])
expected = TRAIN_DIST * N_TEST

In [125]:
predicted = np.array([1215, 1365, 1218, 2055])

In [126]:
# % expected
predicted / expected

array([0.65522166, 0.86559445, 0.62152795, 0.82163271])

In [127]:
# % total
predicted / N_TEST

array([0.32855598, 0.36911844, 0.32936723, 0.55570579])

In [57]:
def compute_top_threshold(t0, c_factor, classification_output):
    return t0 - 2 * c_factor * (classification_output - 0.5)

In [61]:
compute_top_threshold(0.5, 0.02, 0)

0.52